#if !canImport(ObjectiveC)
import XCTest

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testContentTypeConversion", testContentTypeConversion),
        ("testInitializationWithDefaultValue", testInitializationWithDefaultValue),
        ("testInitializationWithInvalidValue", testInitializationWithInvalidValue),
        ("testJSONAdd", testJSONAdd),
        ("testJSONEquality", testJSONEquality),
        ("testJSONInEquality", testJSONInEquality),
        ("testJSONMDivide", testJSONMDivide),
        ("testJSONMInitializationFromLiteral", testJSONMInitializationFromLiteral),
        ("testJSONMInitializationFromValue", testJSONMInitializationFromValue),
        ("testJSONMinus", testJSONMinus),
        ("testJSONMLessThan", testJSONMLessThan),
        ("testJSONMModulo", testJSONMModulo),
        ("testJSONMultiply", testJSONMultiply),
        ("testJSONStrictEquality", testJSONStrictEquality),
        ("testJSONStrictInEquality", testJSONStrictInEquality),
        ("testJSONSubscriptGet_GivenJSONArray", testJSONSubscriptGet_GivenJSONArray),
        ("testJSONSubscriptGet_GivenJSONDictionary", testJSONSubscriptGet_GivenJSONDictionary),
        ("testJSONSubscriptSet_GivenJSONArray", testJSONSubscriptSet_GivenJSONArray),
        ("testJSONSubscriptSet_GivenJSONDictionary", testJSONSubscriptSet_GivenJSONDictionary),
        ("testJSONSubscriptSetPadsArrayWithNil_WhenIndexIsOutOfRange_GivenJSONArray", testJSONSubscriptSetPadsArrayWithNil_WhenIndexIsOutOfRange_GivenJSONArray),
        ("testToNumberConversion", testToNumberConversion),
        ("testTruthy", testTruthy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONTests.__allTests__JSONTests),
    ]
}
#endif
