#if !canImport(ObjectiveC)
import XCTest

extension AllTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AllTests = [
        ("testAll_withCurrentArrayElement", testAll_withCurrentArrayElement),
        ("testAll_withEmptyDataArray", testAll_withEmptyDataArray),
        ("testAll_withNestedArrayElement", testAll_withNestedArrayElement),
    ]
}

extension AndTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AndTests = [
        ("testAnd_mixedArguments", testAnd_mixedArguments),
        ("testAnd_twoBooleans", testAnd_twoBooleans),
    ]
}

extension Arithmetic {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Arithmetic = [
        ("testAddition", testAddition),
        ("testDivision", testDivision),
        ("testModulo", testModulo),
        ("testMultiplication", testMultiplication),
        ("testMultiplication_TypeCoercion", testMultiplication_TypeCoercion),
        ("testSubtraction", testSubtraction),
        ("testUnaryMinus", testUnaryMinus),
    ]
}

extension ArrayMapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayMapTests = [
        ("testFilter", testFilter),
        ("testMap", testMap),
        ("testReduce", testReduce),
    ]
}

extension BetweenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BetweenTests = [
        ("testBetween_withNumberConstants", testBetween_withNumberConstants),
        ("testBetween_withVariables", testBetween_withVariables),
    ]
}

extension CatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CatTests = [
        ("testCat", testCat),
        ("testCat_WithArrays", testCat_WithArrays),
        ("testCat_WithBoolean", testCat_WithBoolean),
        ("testCat_WithNullOrEmpty", testCat_WithNullOrEmpty),
    ]
}

extension CompoundTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompoundTests = [
        ("testCompound", testCompound),
    ]
}

extension CustomOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomOperatorTests = [
        ("testCustomOperatorIsCalled_GivenItIsRegisted", testCustomOperatorIsCalled_GivenItIsRegisted),
        ("testCustomOperatorIsGivenExpetedJSONToEvaluate", testCustomOperatorIsGivenExpetedJSONToEvaluate),
        ("testCustomOperatorIsNotCalled_GivenItIsNotRegisted", testCustomOperatorIsNotCalled_GivenItIsNotRegisted),
        ("testCustomOperatorIsNotCalled_GivenItIsRegistedWithSameNameAsInternalOperators", testCustomOperatorIsNotCalled_GivenItIsRegistedWithSameNameAsInternalOperators),
    ]
}

extension ucviTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ucviTests = [
      ("testUVCI", testUVCI),
    ]
}

extension DoubleNegationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DoubleNegationTests = [
        ("testDoubleNegation_withArrays", testDoubleNegation_withArrays),
        ("testDoubleNegation_withBooleans", testDoubleNegation_withBooleans),
        ("testDoubleNegation_withNull", testDoubleNegation_withNull),
        ("testDoubleNegation_withNumbers", testDoubleNegation_withNumbers),
        ("testDoubleNegation_withStrings", testDoubleNegation_withStrings),
    ]
}

extension EqualsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EqualsTests = [
        ("testEquals", testEquals),
        ("testEquals_WithTypeCoercion", testEquals_WithTypeCoercion),
        ("testNotEquals", testNotEquals),
        ("testNotEquals_WithTypeCoersion", testNotEquals_WithTypeCoersion),
    ]
}

extension GreaterThanOrEqualTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterThanOrEqualTests = [
        ("testGreaterThan_withMixedArgumentTypes", testGreaterThan_withMixedArgumentTypes),
        ("testGreaterThan_withNonNumbericConstants", testGreaterThan_withNonNumbericConstants),
        ("testGreaterThan_withNumberConstants", testGreaterThan_withNumberConstants),
        ("testGreaterThan_withVariables", testGreaterThan_withVariables),
    ]
}

extension GreaterThanTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreaterThanTests = [
        ("testGreaterThan_withMixedArguments", testGreaterThan_withMixedArguments),
        ("testGreaterThan_withNonNumbericConstants", testGreaterThan_withNonNumbericConstants),
        ("testGreaterThan_withNumberConstants", testGreaterThan_withNumberConstants),
        ("testGreaterThan_withVariables", testGreaterThan_withVariables),
    ]
}

extension IfTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IfTests = [
        ("testIf_EmptyArraysAreFalsey", testIf_EmptyArraysAreFalsey),
        ("testIf_FizzBuzz", testIf_FizzBuzz),
        ("testIf_IfThenElseIfThenCases", testIf_IfThenElseIfThenCases),
        ("testIf_NonEmptyOtherStringsAreTruthy", testIf_NonEmptyOtherStringsAreTruthy),
        ("testIf_SimpleCases", testIf_SimpleCases),
        ("testIf_ToofewArgs", testIf_ToofewArgs),
    ]
}

extension InTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InTests = [
        ("testIn_ArrayArgument", testIn_ArrayArgument),
        ("testIn_StringArgument", testIn_StringArgument),
    ]
}

extension JsonLogicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JsonLogicTests = [
        ("testAddTwoIntsFromVariables", testAddTwoIntsFromVariables),
        ("testEqualsWithDifferentSameConstants", testEqualsWithDifferentSameConstants),
        ("testEqualsWithTwoSameConstants", testEqualsWithTwoSameConstants),
        ("testNestedStrictEqualsWithVar", testNestedStrictEqualsWithVar),
        ("testNestedVar", testNestedVar),
        ("testNestedVarWithStrictEquals", testNestedVarWithStrictEquals),
        ("testNotSupportedResultType", testNotSupportedResultType),
        ("testSetOneBoolVariableFromData", testSetOneBoolVariableFromData),
        ("testSetOneIntegerVariableFromData", testSetOneIntegerVariableFromData),
        ("testSetOneStringArrayVariableFromData", testSetOneStringArrayVariableFromData),
        ("testSetOneStringNestedVariableFromData", testSetOneStringNestedVariableFromData),
        ("testSetOneStringVariableFromData", testSetOneStringVariableFromData),
        ("testSetTwoStringVariablesFromData", testSetTwoStringVariablesFromData),
    ]
}

extension LessThanOrEqualTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessThanOrEqualTests = [
        ("testLessThan_withMixedArgumentTypes", testLessThan_withMixedArgumentTypes),
        ("testLessThan_withNonNumericConstants", testLessThan_withNonNumericConstants),
        ("testLessThan_withNumberConstants", testLessThan_withNumberConstants),
        ("testLessThan_withVariables", testLessThan_withVariables),
    ]
}

extension LessThanTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LessThanTests = [
        ("testLessThan_withMixedArgumentsTypes", testLessThan_withMixedArgumentsTypes),
        ("testLessThan_withNonNumbericConstants", testLessThan_withNonNumbericConstants),
        ("testLessThan_withNumberConstants", testLessThan_withNumberConstants),
        ("testLessThan_withVariables", testLessThan_withVariables),
    ]
}

extension LogTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogTests = [
        ("testLog", testLog),
        ("testLog_nestedInOtherExpressions", testLog_nestedInOtherExpressions),
        ("testLog_withComplexExpression", testLog_withComplexExpression),
    ]
}

extension MergeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MergeTests = [
        ("testMerge", testMerge),
        ("testMerge_withNonArrayArguments", testMerge_withNonArrayArguments),
    ]
}

extension MinMaxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MinMaxTests = [
        ("testMax_MultipleNegativeValues", testMax_MultipleNegativeValues),
        ("testMax_MultiplePositiveValues", testMax_MultiplePositiveValues),
        ("testMax_SinglePositiveItem", testMax_SinglePositiveItem),
        ("testMin_MultipleNegativeValues", testMin_MultipleNegativeValues),
        ("testMin_MultiplePositiveValues", testMin_MultiplePositiveValues),
        ("testMin_SinglePositiveItem", testMin_SinglePositiveItem),
    ]
}

extension MissingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MissingTests = [
        ("testMissing", testMissing),
        ("testMissing_NestedKeys", testMissing_NestedKeys),
        ("testMissing_some", testMissing_some),
        ("testVar_withEmptyVarName", testVar_withEmptyVarName),
    ]
}

extension NoneTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoneTests = [
        ("testNone", testNone),
        ("testNone_WithEmptyDataArray", testNone_WithEmptyDataArray),
        ("testNone_WithNestedDataItems", testNone_WithNestedDataItems),
    ]
}

extension NotStrictEquals {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NotStrictEquals = [
        ("testLogicalNot_withArrays", testLogicalNot_withArrays),
        ("testLogicalNot_withBooleanConstants", testLogicalNot_withBooleanConstants),
        ("testLogicalNot_withNull", testLogicalNot_withNull),
        ("testLogicalNot_withNumbers", testLogicalNot_withNumbers),
        ("testLogicalNot_withStrings", testLogicalNot_withStrings),
        ("testLogicalNot_withVariables", testLogicalNot_withVariables),
        ("testNot_StrictEquals_withConstants", testNot_StrictEquals_withConstants),
        ("testNot_StrictEquals_withConstants1", testNot_StrictEquals_withConstants1),
        ("testNot_StrictEquals_withConstants2", testNot_StrictEquals_withConstants2),
        ("testNot_StrictEquals_withConstants3", testNot_StrictEquals_withConstants3),
        ("testNotStringEquals_NestedVar", testNotStringEquals_NestedVar),
    ]
}

extension OrTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrTests = [
        ("testOr_mixedArguments", testOr_mixedArguments),
        ("testOr_twoBooleans", testOr_twoBooleans),
    ]
}

extension SomeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SomeTests = [
        ("testNone_WithNestedDataItems", testNone_WithNestedDataItems),
        ("testSome", testSome),
        ("testSome_WithEmptyDataArray", testSome_WithEmptyDataArray),
    ]
}

extension SubstringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubstringTests = [
        ("testSubstring", testSubstring),
        ("testSubstring_withRange", testSubstring_withRange),
        ("testSunString_withInvalidLength", testSunString_withInvalidLength),
        ("testSunString_withInvalidStart", testSunString_withInvalidStart),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AllTests.__allTests__AllTests),
        testCase(AndTests.__allTests__AndTests),
        testCase(Arithmetic.__allTests__Arithmetic),
        testCase(ArrayMapTests.__allTests__ArrayMapTests),
        testCase(BetweenTests.__allTests__BetweenTests),
        testCase(CatTests.__allTests__CatTests),
        testCase(CompoundTests.__allTests__CompoundTests),
        testCase(CustomOperatorTests.__allTests__CustomOperatorTests),
        testCase(ucviTests.__allTests__ucviTests),
        testCase(DoubleNegationTests.__allTests__DoubleNegationTests),
        testCase(EqualsTests.__allTests__EqualsTests),
        testCase(GreaterThanOrEqualTests.__allTests__GreaterThanOrEqualTests),
        testCase(GreaterThanTests.__allTests__GreaterThanTests),
        testCase(IfTests.__allTests__IfTests),
        testCase(InTests.__allTests__InTests),
        testCase(JsonLogicTests.__allTests__JsonLogicTests),
        testCase(LessThanOrEqualTests.__allTests__LessThanOrEqualTests),
        testCase(LessThanTests.__allTests__LessThanTests),
        testCase(LogTests.__allTests__LogTests),
        testCase(MergeTests.__allTests__MergeTests),
        testCase(MinMaxTests.__allTests__MinMaxTests),
        testCase(MissingTests.__allTests__MissingTests),
        testCase(NoneTests.__allTests__NoneTests),
        testCase(NotStrictEquals.__allTests__NotStrictEquals),
        testCase(OrTests.__allTests__OrTests),
        testCase(SomeTests.__allTests__SomeTests),
        testCase(SubstringTests.__allTests__SubstringTests),
    ]
}
#endif
